### ISSUE TITLE
RioShiina

### ISSUE THREAD

**Issue by onefive1156** [Yggdrasill-Moe/Longinus#1]
索引未经过zlib压缩，暂不支持此类型!
想问问大佬以后会支持吗

[Guilty+] Ran→Sem ～白濁デルモ妻のミイラ捕り～

**Comment by Darkness-TX** [comment]
RioShiina的问题去看隔壁Niflheim项目的issues，具体游戏具体分析，没有写成啥游戏都能用的通用解包器，想解包用garbro，而且你这提示看应该是老游戏，那更不可能支持了
