### ISSUE TITLE
关于Alicesoft游戏的textout的输出问题

### ISSUE THREAD

**Issue by UESTC-LXY** [Yggdrasill-Moe/Longinus#2]
大佬，最近在研究动态汉化，然后看了下母娘乱馆，发现原版的母娘乱馆文本输出不会调textoutA，但是汉化版会调textoutA，dll源码里面也看不出来这一点， 能说说原理吗

**Comment by Darkness-TX** [comment]
年代久远啊……当时应该是改了ain的脚本，应该没改exe？你可以对比下exe有没有什么变动，A社的引擎似乎在sys4.0后默认都是用的自带字库，首先要让起使用系统字体，然后才会使用textoutA，不然只会使用自带字库来显示字，所以原版没调就是这原因，ain中记得有个专门选择字体的函数，就改的那，我好像还顺手启动了一个函数，让游戏能读增量补丁，所以汉化补丁没有很大

**Comment by UESTC-LXY** [comment]
> 年代久远啊……当时应该是改了ain的脚本，应该没改exe？你可以对比下exe有没有什么变动，A社的引擎似乎在sys4.0后默认都是用的自带字库，首先要让起使用系统字体，然后才会使用textoutA，不然只会使用自带字库来显示字，所以原版没调就是这原因，ain中记得有个专门选择字体的函数，就改的那，我好像还顺手启动了一个函数，让游戏能读增量补丁，所以汉化补丁没有很大

嗯嗯 我对比了下 看了下母娘乱馆改了Mfont和Msize 感谢大佬解答哈   拿母娘的经验 适配到粉毛母上看看

**Comment by Cosetto** [comment]
Sorry to bother this issue again
@UESTC-LXY Hey man, can you unstar and unfork the superengine source code? It's too avoid Visual Art detecting and DMCA
